#!/usr/bin/env node
/**
 * design/motifs/*.svg → lib/motifs.generated.ts
 *
 * A second map beside the category plates, and it exists because the plate generator
 * cannot hold these: `tools/build-blueprints.mjs` KEYS is the nine `CategoryKey`
 * values, and `CategoryPlate` maps them exhaustively. A wine glass or a loaf-shaped
 * loader is not a category, so dropping it in there would either be ignored or break
 * that map.
 *
 * Same drawing language, same inline reason: `currentColor` does not resolve for an
 * SVG loaded as an image, so the markup has to reach the page.
 *
 *   npm run motifs
 */
import { writeFileSync } from 'node:fs';
import { readSvgDir } from './lib/inline-svg.mjs';

const KEYS = [
  'loader_loaf',
  /* The blueprint sweep: every one of these replaced an emoji in the chrome. */
  'chef_hat', 'candle', 'apple', 'search', 'folder', 'clipboard', 'link', 'sparkle',
];

const dir = new URL('../design/motifs/', import.meta.url).pathname;
const out = new URL('../lib/motifs.generated.ts', import.meta.url).pathname;
const entries = readSvgDir(dir, KEYS);

writeFileSync(out, `/* GENERATED by tools/build-motifs.mjs — do not edit.
 * Source: design/motifs/*.svg. Run \`npm run motifs\` after changing one.
 */

export type MotifName = ${KEYS.map((k) => `'${k}'`).join(' | ')};

export const MOTIFS: Record<MotifName, { viewBox: string; inner: string }> = {
${entries.map((e) => `  ${e.key}: {\n    viewBox: ${JSON.stringify(e.viewBox)},\n    inner: ${JSON.stringify(e.inner)},\n  },`).join('\n')}
};
`);
console.log(`wrote lib/motifs.generated.ts — ${entries.length} motifs`);
