#!/usr/bin/env node
/**
 * design/icons/*.svg → lib/icons.generated.ts
 *
 * Replaces the emoji that were standing in for iconography. Emoji are somebody
 * else's artwork in somebody else's font: they differ per platform, they are
 * full-colour, and beside the engraved plates they read as a different app. ⚙ and
 * ✒️ did not even match each other in weight.
 *
 *   npm run icons
 */
import { writeFileSync } from 'node:fs';
import { readSvgDir } from './lib/inline-svg.mjs';

const KEYS = [
  'home', 'recipes', 'menus', 'add',              // the nav bar
  'kids_bear', 'menu_candle', 'add_recipe', 'settings',  // the homepage actions
];

const dir = new URL('../design/icons/', import.meta.url).pathname;
const out = new URL('../lib/icons.generated.ts', import.meta.url).pathname;
const entries = readSvgDir(dir, KEYS);

writeFileSync(out, `/* GENERATED by tools/build-icons.mjs — do not edit.
 * Source: design/icons/*.svg. Run \`npm run icons\` after changing one.
 */

export type IconName = ${KEYS.map((k) => `'${k}'`).join(' | ')};

export type Icon = { viewBox: string; inner: string };

export const ICONS: Record<IconName, Icon> = {
${entries.map((e) => `  ${e.key}: {\n    viewBox: ${JSON.stringify(e.viewBox)},\n    inner: ${JSON.stringify(e.inner)},\n  },`).join('\n')}
};
`);
console.log(`wrote lib/icons.generated.ts — ${entries.length} icons`);
