/* GENERATED by tools/build-blueprints.mjs — do not edit.
 * Source: design/blueprints/*.svg. Run `npm run blueprints` after changing one.
 */
import type { CategoryKey } from './constants';

export type Blueprint = { viewBox: string; inner: string };

export const BLUEPRINTS: Record<CategoryKey, Blueprint> = {
  entrees: {
    viewBox: "0 0 110 90",
    inner: "<ellipse cx=\"55\" cy=\"58\" rx=\"40\" ry=\"14\"></ellipse><ellipse cx=\"55\" cy=\"58\" rx=\"26\" ry=\"8\" stroke-dasharray=\"3 3\"></ellipse><path d=\"M40 52 Q45 40 55 42 Q68 44 66 53\" stroke-width=\"1.2\"></path><path d=\"M50 34 q2 -6 0 -10 M58 36 q2 -6 0 -10\" stroke-width=\"1\" opacity=\".6\"></path>",
  },
  soups: {
    viewBox: "0 0 110 90",
    inner: "<path d=\"M25 45 h60 a0 0 0 0 1 -8 26 q-4 8 -22 8 t-22 -8 a30 30 0 0 1 -8 -26 Z\"></path><path d=\"M32 51 h46\" stroke-dasharray=\"3 3\" stroke-width=\"1\"></path><path d=\"M85 48 q14 -2 12 8 q-2 8 -13 4\" stroke-width=\"1.2\"></path><path d=\"M45 36 q2 -6 0 -10 M55 38 q2 -7 0 -12 M65 36 q2 -6 0 -10\" stroke-width=\"1\" opacity=\".6\"></path>",
  },
  salads: {
    viewBox: "0 0 110 90",
    inner: "<path d=\"M30 50 a26 26 0 0 0 50 0\"></path><path d=\"M30 50 h50\" stroke-width=\"1\"></path><path d=\"M42 44 q6 -10 14 -6 M56 42 q8 -8 14 -2 M48 38 q4 -8 10 -8\" stroke-width=\"1.2\"></path><path d=\"M38 46 l-8 -14 M74 46 l6 -12\" stroke-width=\"1\" opacity=\".6\"></path>",
  },
  mains: {
    viewBox: "0 0 110 90",
    inner: "<ellipse cx=\"55\" cy=\"62\" rx=\"42\" ry=\"12\"></ellipse><path d=\"M30 58 a30 22 0 0 1 50 0\"></path><path d=\"M55 36 v-8 m0 0 a4 4 0 1 1 .1 0\" stroke-width=\"1.2\"></path><path d=\"M22 62 q-8 0 -10 -4 M88 62 q8 0 10 -4\" stroke-width=\"1\" opacity=\".6\"></path>",
  },
  sides: {
    viewBox: "0 0 110 90",
    inner: "<rect x=\"28\" y=\"44\" width=\"54\" height=\"24\" rx=\"4\"></rect><path d=\"M28 52 h54\" stroke-width=\"1\" stroke-dasharray=\"3 3\"></path><path d=\"M24 48 q-6 4 0 8 M86 48 q6 4 0 8\" stroke-width=\"1.2\"></path><path d=\"M40 38 q2 -6 0 -10 M55 40 q2 -7 0 -12 M70 38 q2 -6 0 -10\" stroke-width=\"1\" opacity=\".6\"></path>",
  },
  breads: {
    viewBox: "0 0 110 90",
    inner: "<path d=\"M26 62 q0 -22 29 -22 t29 22 Z\"></path><path d=\"M22 62 h66 a4 4 0 0 1 -4 8 H26 a4 4 0 0 1 -4 -8 Z\"></path><path d=\"M40 50 l-5 10 M55 47 l-5 13 M70 50 l-5 10\" stroke-width=\"1\" stroke-dasharray=\"3 3\"></path><path d=\"M44 34 q2 -6 0 -10 M66 34 q2 -6 0 -10\" stroke-width=\"1\" opacity=\".6\"></path>",
  },
  desserts: {
    viewBox: "0 0 110 90",
    inner: "<path d=\"M38 60 h34 l-4 -20 a13 13 0 0 0 -26 0 Z\"></path><path d=\"M42 40 q13 -8 26 0\" stroke-width=\"1\" stroke-dasharray=\"3 3\"></path><path d=\"M55 30 q0 -6 5 -8\" stroke-width=\"1.2\"></path><ellipse cx=\"55\" cy=\"66\" rx=\"26\" ry=\"5\" stroke-width=\"1\"></ellipse>",
  },
  kids: {
    viewBox: "0 0 110 90",
    inner: "<circle cx=\"55\" cy=\"48\" r=\"18\"></circle><circle cx=\"42\" cy=\"34\" r=\"7\"></circle><circle cx=\"68\" cy=\"34\" r=\"7\"></circle><circle cx=\"50\" cy=\"46\" r=\"1.5\" fill=\"currentColor\"></circle><circle cx=\"60\" cy=\"46\" r=\"1.5\" fill=\"currentColor\"></circle><path d=\"M50 54 q5 4 10 0\" stroke-width=\"1.2\"></path><path d=\"M84 60 q6 -8 12 0 q-6 8 -12 0 M92 56 v8\" stroke-width=\"1\" opacity=\".7\"></path>",
  },
  sauces: {
    viewBox: "0 0 110 90",
    inner: "<!-- A sauce boat, continuing the printed series. Drawn to the same conventions as the     other nine: one weight for the object, 1.2 for its handle and spout, a dashed     hairline for the level inside, and a 0.6-opacity flourish above. --><path d=\"M30 48 h48 q-3 20 -14 22 H44 q-11 -2 -14 -22 Z\"></path><path d=\"M78 50 q10 -4 14 2 q-3 5 -11 4\" stroke-width=\"1.2\"></path><path d=\"M30 48 q-9 -3 -12 3 q3 6 11 5\" stroke-width=\"1.2\"></path><path d=\"M36 55 h36\" stroke-width=\"1\" stroke-dasharray=\"3 3\"></path><path d=\"M50 42 q3 -6 0 -11 M62 42 q3 -5 0 -9\" stroke-width=\"1\" opacity=\".6\"></path><path d=\"M36 74 h36\" stroke-width=\"1\" opacity=\".45\"></path>",
  },
  other: {
    viewBox: "0 0 110 90",
    inner: "<path d=\"M40 28 v34 M36 28 v10 M44 28 v10\" stroke-width=\"1.2\"></path><path d=\"M36 38 q4 4 8 0\"></path><path d=\"M68 28 q8 4 8 14 q0 8 -6 10 v10\"></path><ellipse cx=\"55\" cy=\"70\" rx=\"32\" ry=\"6\" stroke-width=\"1\" stroke-dasharray=\"3 3\"></ellipse>",
  },
};
