/* GENERATED by tools/build-icons.mjs — do not edit.
 * Source: design/icons/*.svg. Run `npm run icons` after changing one.
 */

export type IconName = 'home' | 'recipes' | 'menus' | 'add' | 'kids_bear' | 'menu_candle' | 'add_recipe' | 'settings';

export type Icon = { viewBox: string; inner: string };

export const ICONS: Record<IconName, Icon> = {
  home: {
    viewBox: "0 0 64 64",
    inner: "<path d=\"M12 30 L32 12 L52 30\"></path><path d=\"M18 26 v24 h28 V26\"></path><path d=\"M27 50 v-14 h10 v14\"></path>",
  },
  recipes: {
    viewBox: "0 0 64 64",
    inner: "<path d=\"M16 10 h26 a6 6 0 0 1 6 6 v38 H22 a6 6 0 0 1 -6 -6z\"></path><path d=\"M22 54 a6 6 0 0 1 0 -12 h26\"></path><path d=\"M26 22 h14 M26 30 h14\"></path>",
  },
  menus: {
    viewBox: "0 0 64 64",
    inner: "<path d=\"M18 8 h28 v48 H18z\"></path><path d=\"M32 18 l5 5 -5 5 -5 -5z\"></path><path d=\"M24 36 h16 M27 45 h10\"></path>",
  },
  add: {
    viewBox: "0 0 64 64",
    inner: "<circle cx=\"32\" cy=\"32\" r=\"21\"></circle><path d=\"M32 22 v20 M22 32 h20\"></path>",
  },
  kids_bear: {
    viewBox: "0 0 64 64",
    inner: "<circle cx=\"32\" cy=\"36\" r=\"15\"></circle><circle cx=\"21\" cy=\"24\" r=\"6\"></circle><circle cx=\"43\" cy=\"24\" r=\"6\"></circle><circle cx=\"28\" cy=\"34\" r=\"1.2\" fill=\"currentColor\"></circle><circle cx=\"36\" cy=\"34\" r=\"1.2\" fill=\"currentColor\"></circle><path d=\"M28 41 q4 3 8 0\"></path>",
  },
  menu_candle: {
    viewBox: "0 0 64 64",
    inner: "<path d=\"M32 20 c-3.5 -3.5 3.5 -5.5 0 -9\"></path><path d=\"M29 26 h6 v20 h-6z\"></path><path d=\"M22 46 h20 M26 50 h12\"></path>",
  },
  add_recipe: {
    viewBox: "0 0 64 64",
    inner: "<path d=\"M18 46 L42 22 l6 6 L24 52 l-8 2z\"></path><path d=\"M40 24 l6 6\"></path><path d=\"M16 54 h32\" opacity=\".6\"></path>",
  },
  settings: {
    viewBox: "0 0 64 64",
    inner: "<circle cx=\"32\" cy=\"32\" r=\"8\"></circle><path d=\"M32 14 v6 M32 44 v6 M14 32 h6 M44 32 h6 M19 19 l4.5 4.5 M40.5 40.5 L45 45 M45 19 l-4.5 4.5 M23.5 40.5 L19 45\"></path>",
  },
};
