/* GENERATED by tools/build-kids-art.mjs — do not edit.
 * Source: design/kids/*.svg. Run `npm run kids-art` after changing one.
 */

export type KidsArtName = 'bear' | 'dog' | 'cat' | 'elephant' | 'rabbit' | 'fox' | 'owl' | 'butterfly' | 'balloon' | 'child';

export const KIDS_ART: Record<KidsArtName, { viewBox: string; inner: string }> = {
  bear: {
    viewBox: "0 0 64 64",
    inner: "<circle cx=\"32\" cy=\"36\" r=\"15\"></circle><circle cx=\"21\" cy=\"24\" r=\"6\"></circle><circle cx=\"43\" cy=\"24\" r=\"6\"></circle><circle cx=\"28\" cy=\"34\" r=\"1.2\" fill=\"currentColor\"></circle><circle cx=\"36\" cy=\"34\" r=\"1.2\" fill=\"currentColor\"></circle><path d=\"M28 41 q4 3 8 0\"></path>",
  },
  dog: {
    viewBox: "0 0 64 64",
    inner: "<circle cx=\"32\" cy=\"36\" r=\"15\"></circle><path d=\"M19 25 q-5 -3 -5 8 q0 7 6 6\"></path><path d=\"M45 25 q5 -3 5 8 q0 7 -6 6\"></path><circle cx=\"27\" cy=\"34\" r=\"1.2\" fill=\"currentColor\"></circle><circle cx=\"37\" cy=\"34\" r=\"1.2\" fill=\"currentColor\"></circle><path d=\"M32 39 v3 M28 44 q4 3 8 0\"></path>",
  },
  cat: {
    viewBox: "0 0 64 64",
    inner: "<circle cx=\"32\" cy=\"37\" r=\"14\"></circle><path d=\"M20 27 l-2 -12 10 6\"></path><path d=\"M44 27 l2 -12 -10 6\"></path><circle cx=\"27\" cy=\"35\" r=\"1.2\" fill=\"currentColor\"></circle><circle cx=\"37\" cy=\"35\" r=\"1.2\" fill=\"currentColor\"></circle><path d=\"M32 40 q-3 3 -6 1 M32 40 q3 3 6 1\"></path><path d=\"M14 36 h6 M44 36 h6\"></path>",
  },
  elephant: {
    viewBox: "0 0 64 64",
    inner: "<path d=\"M22 22 a12 12 0 0 1 20 0 v14 a10 10 0 0 1 -6 9\"></path><path d=\"M36 45 q1 8 -4 9 t-5 -6\"></path><path d=\"M22 24 q-9 -4 -10 6 t8 10\"></path><path d=\"M42 24 q9 -4 10 6 t-8 10\"></path><circle cx=\"27\" cy=\"28\" r=\"1.3\" fill=\"currentColor\"></circle><circle cx=\"37\" cy=\"28\" r=\"1.3\" fill=\"currentColor\"></circle>",
  },
  rabbit: {
    viewBox: "0 0 64 64",
    inner: "<circle cx=\"32\" cy=\"40\" r=\"13\"></circle><path d=\"M25 28 q-3 -16 2 -18 t3 15\"></path><path d=\"M39 28 q3 -16 -2 -18 t-3 15\"></path><circle cx=\"28\" cy=\"38\" r=\"1.2\" fill=\"currentColor\"></circle><circle cx=\"36\" cy=\"38\" r=\"1.2\" fill=\"currentColor\"></circle><path d=\"M32 42 v2 M29 46 q3 2 6 0\"></path>",
  },
  fox: {
    viewBox: "0 0 64 64",
    inner: "<path d=\"M18 26 L24 12 l8 8 8 -8 6 14 a14 14 0 0 1 -28 0z\"></path><path d=\"M18 26 a14 14 0 0 0 28 0\"></path><circle cx=\"27\" cy=\"32\" r=\"1.2\" fill=\"currentColor\"></circle><circle cx=\"37\" cy=\"32\" r=\"1.2\" fill=\"currentColor\"></circle><path d=\"M32 38 v3 M28 44 q4 3 8 0\"></path>",
  },
  owl: {
    viewBox: "0 0 64 64",
    inner: "<path d=\"M32 12 a16 18 0 0 1 16 18 v10 a16 16 0 0 1 -32 0 V30 a16 18 0 0 1 16 -18z\"></path><circle cx=\"25\" cy=\"30\" r=\"6\"></circle><circle cx=\"39\" cy=\"30\" r=\"6\"></circle><circle cx=\"25\" cy=\"30\" r=\"1.4\" fill=\"currentColor\"></circle><circle cx=\"39\" cy=\"30\" r=\"1.4\" fill=\"currentColor\"></circle><path d=\"M32 36 l-3 4 h6z\"></path><path d=\"M18 18 l4 6 M46 18 l-4 6\"></path>",
  },
  butterfly: {
    viewBox: "0 0 64 64",
    inner: "<path d=\"M32 22 v22\"></path><path d=\"M32 26 q-14 -14 -19 -3 t8 16 q8 3 11 -5z\"></path><path d=\"M32 26 q14 -14 19 -3 t-8 16 q-8 3 -11 -5z\"></path><path d=\"M32 22 l-5 -7 M32 22 l5 -7\"></path>",
  },
  balloon: {
    viewBox: "0 0 64 64",
    inner: "<ellipse cx=\"32\" cy=\"24\" rx=\"14\" ry=\"17\"></ellipse><path d=\"M29 41 h6 l-3 4z\"></path><path d=\"M32 45 q6 6 0 12 t0 6\"></path>",
  },
  child: {
    viewBox: "0 0 64 64",
    inner: "<circle cx=\"32\" cy=\"22\" r=\"12\"></circle><path d=\"M20 18 q12 -10 24 0\"></path><circle cx=\"27\" cy=\"22\" r=\"1.3\" fill=\"currentColor\"></circle><circle cx=\"37\" cy=\"22\" r=\"1.3\" fill=\"currentColor\"></circle><path d=\"M27 27 q5 5 10 0\"></path><path d=\"M32 34 v12 M32 38 l-9 6 M32 38 l9 6 M32 46 l-6 10 M32 46 l6 10\"></path>",
  },
};
